[
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -std=gnu++11 -MD -MT src/sfdk/CMakeFiles/sfdkobj.dir/lib/cryptocontextfactory-sfdk-impl.cpp.o -MF CMakeFiles/sfdkobj.dir/lib/cryptocontextfactory-sfdk-impl.cpp.o.d -o CMakeFiles/sfdkobj.dir/lib/cryptocontextfactory-sfdk-impl.cpp.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib/cryptocontextfactory-sfdk-impl.cpp",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib/cryptocontextfactory-sfdk-impl.cpp"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -std=gnu++11 -MD -MT src/sfdk/CMakeFiles/sfdkobj.dir/lib/scheme/bfvrns-sfdk/bfvrns-sfdk-impl.cpp.o -MF CMakeFiles/sfdkobj.dir/lib/scheme/bfvrns-sfdk/bfvrns-sfdk-impl.cpp.o.d -o CMakeFiles/sfdkobj.dir/lib/scheme/bfvrns-sfdk/bfvrns-sfdk-impl.cpp.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib/scheme/bfvrns-sfdk/bfvrns-sfdk-impl.cpp",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib/scheme/bfvrns-sfdk/bfvrns-sfdk-impl.cpp"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT src/sfdk/CMakeFiles/sfdk_tests.dir/unittest/UnitTestBFVrnsDecryptSFDK.cpp.o -MF CMakeFiles/sfdk_tests.dir/unittest/UnitTestBFVrnsDecryptSFDK.cpp.o.d -o CMakeFiles/sfdk_tests.dir/unittest/UnitTestBFVrnsDecryptSFDK.cpp.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/unittest/UnitTestBFVrnsDecryptSFDK.cpp",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/unittest/UnitTestBFVrnsDecryptSFDK.cpp"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/src/sfdk/lib -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT src/sfdk/CMakeFiles/sfdk_tests.dir/__/__/test/Main_TestAll.cpp.o -MF CMakeFiles/sfdk_tests.dir/__/__/test/Main_TestAll.cpp.o.d -o CMakeFiles/sfdk_tests.dir/__/__/test/Main_TestAll.cpp.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/test/Main_TestAll.cpp",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/test/Main_TestAll.cpp"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o -MF CMakeFiles/benchmark.dir/benchmark.cc.o.d -o CMakeFiles/benchmark.dir/benchmark.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/benchmark_api_internal.cc.o -MF CMakeFiles/benchmark.dir/benchmark_api_internal.cc.o.d -o CMakeFiles/benchmark.dir/benchmark_api_internal.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_api_internal.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_api_internal.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/benchmark_name.cc.o -MF CMakeFiles/benchmark.dir/benchmark_name.cc.o.d -o CMakeFiles/benchmark.dir/benchmark_name.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_name.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_name.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o -MF CMakeFiles/benchmark.dir/benchmark_register.cc.o.d -o CMakeFiles/benchmark.dir/benchmark_register.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_register.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_register.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/benchmark_runner.cc.o -MF CMakeFiles/benchmark.dir/benchmark_runner.cc.o.d -o CMakeFiles/benchmark.dir/benchmark_runner.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_runner.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_runner.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/colorprint.cc.o -MF CMakeFiles/benchmark.dir/colorprint.cc.o.d -o CMakeFiles/benchmark.dir/colorprint.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/colorprint.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/colorprint.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/commandlineflags.cc.o -MF CMakeFiles/benchmark.dir/commandlineflags.cc.o.d -o CMakeFiles/benchmark.dir/commandlineflags.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/commandlineflags.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/commandlineflags.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/complexity.cc.o -MF CMakeFiles/benchmark.dir/complexity.cc.o.d -o CMakeFiles/benchmark.dir/complexity.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/complexity.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/complexity.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/console_reporter.cc.o -MF CMakeFiles/benchmark.dir/console_reporter.cc.o.d -o CMakeFiles/benchmark.dir/console_reporter.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/console_reporter.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/console_reporter.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/counter.cc.o -MF CMakeFiles/benchmark.dir/counter.cc.o.d -o CMakeFiles/benchmark.dir/counter.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/counter.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/counter.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/csv_reporter.cc.o -MF CMakeFiles/benchmark.dir/csv_reporter.cc.o.d -o CMakeFiles/benchmark.dir/csv_reporter.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/csv_reporter.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/csv_reporter.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/json_reporter.cc.o -MF CMakeFiles/benchmark.dir/json_reporter.cc.o.d -o CMakeFiles/benchmark.dir/json_reporter.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/json_reporter.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/json_reporter.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/perf_counters.cc.o -MF CMakeFiles/benchmark.dir/perf_counters.cc.o.d -o CMakeFiles/benchmark.dir/perf_counters.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/perf_counters.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/perf_counters.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/reporter.cc.o -MF CMakeFiles/benchmark.dir/reporter.cc.o.d -o CMakeFiles/benchmark.dir/reporter.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/reporter.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/reporter.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/sleep.cc.o -MF CMakeFiles/benchmark.dir/sleep.cc.o.d -o CMakeFiles/benchmark.dir/sleep.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/sleep.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/sleep.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/statistics.cc.o -MF CMakeFiles/benchmark.dir/statistics.cc.o.d -o CMakeFiles/benchmark.dir/statistics.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/statistics.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/statistics.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/string_util.cc.o -MF CMakeFiles/benchmark.dir/string_util.cc.o.d -o CMakeFiles/benchmark.dir/string_util.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/string_util.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/string_util.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/sysinfo.cc.o -MF CMakeFiles/benchmark.dir/sysinfo.cc.o.d -o CMakeFiles/benchmark.dir/sysinfo.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/sysinfo.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/sysinfo.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark.dir/timers.cc.o -MF CMakeFiles/benchmark.dir/timers.cc.o.d -o CMakeFiles/benchmark.dir/timers.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/timers.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/timers.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/../include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=gnu++11 -MD -MT third-party/google-benchmark/src/CMakeFiles/benchmark_main.dir/benchmark_main.cc.o -MF CMakeFiles/benchmark_main.dir/benchmark_main.cc.o.d -o CMakeFiles/benchmark_main.dir/benchmark_main.cc.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_main.cc",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-benchmark/src/benchmark_main.cc"
    },
    {
        "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/usr/local/opt/libomp/include -I/usr/local/include/palisade -I/usr/local/include/palisade/third-party/include -I/usr/local/include/palisade/core -I/usr/local/include/palisade/pke -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/third-party/google-test/googletest/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../src/core/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../src/core/lib -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../src/pke/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../src/binfhe/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../src/sfdk/include -I/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/../third-party/google-benchmark/include -Wall -Werror -O3  -DPALISADE_VERSION=1.11.7  -Wno-unused-private-field -Wno-shift-op-parentheses -DMATHBACKEND=2 -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Xpreprocessor -fopenmp -lomp -Wno-unused-command-line-argument -Wall -Werror -O3   -Wno-unused-private-field -Wno-shift-op-parentheses -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DNDEBUG  -std=gnu++11 -MD -MT benchmark/CMakeFiles/lib-benchmark.dir/src/lib-benchmark.cpp.o -MF CMakeFiles/lib-benchmark.dir/src/lib-benchmark.cpp.o.d -o CMakeFiles/lib-benchmark.dir/src/lib-benchmark.cpp.o -c /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/src/lib-benchmark.cpp",
        "directory": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk",
        "file": "/Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/benchmark/src/lib-benchmark.cpp"
    }
]