# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/CMakeFiles /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named allmodules

# Build rule for target.
allmodules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allmodules
.PHONY : allmodules

# fast build rule for target.
allmodules/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allmodules.dir/build.make CMakeFiles/allmodules.dir/build
.PHONY : allmodules/fast

#=============================================================================
# Target rules for targets named sfdkobj

# Build rule for target.
sfdkobj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfdkobj
.PHONY : sfdkobj

# fast build rule for target.
sfdkobj/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/sfdkobj.dir/build.make src/sfdk/CMakeFiles/sfdkobj.dir/build
.PHONY : sfdkobj/fast

#=============================================================================
# Target rules for targets named PALISADEsfdk

# Build rule for target.
PALISADEsfdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PALISADEsfdk
.PHONY : PALISADEsfdk

# fast build rule for target.
PALISADEsfdk/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/PALISADEsfdk.dir/build.make src/sfdk/CMakeFiles/PALISADEsfdk.dir/build
.PHONY : PALISADEsfdk/fast

#=============================================================================
# Target rules for targets named allsfdk

# Build rule for target.
allsfdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allsfdk
.PHONY : allsfdk

# fast build rule for target.
allsfdk/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/allsfdk.dir/build.make src/sfdk/CMakeFiles/allsfdk.dir/build
.PHONY : allsfdk/fast

#=============================================================================
# Target rules for targets named simple-integers

# Build rule for target.
simple-integers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-integers
.PHONY : simple-integers

# fast build rule for target.
simple-integers/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/simple-integers.dir/build.make src/sfdk/CMakeFiles/simple-integers.dir/build
.PHONY : simple-integers/fast

#=============================================================================
# Target rules for targets named allsfdkexamples

# Build rule for target.
allsfdkexamples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allsfdkexamples
.PHONY : allsfdkexamples

# fast build rule for target.
allsfdkexamples/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/allsfdkexamples.dir/build.make src/sfdk/CMakeFiles/allsfdkexamples.dir/build
.PHONY : allsfdkexamples/fast

#=============================================================================
# Target rules for targets named sfdk_tests

# Build rule for target.
sfdk_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfdk_tests
.PHONY : sfdk_tests

# fast build rule for target.
sfdk_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/sfdk_tests.dir/build.make src/sfdk/CMakeFiles/sfdk_tests.dir/build
.PHONY : sfdk_tests/fast

#=============================================================================
# Target rules for targets named testsfdk

# Build rule for target.
testsfdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testsfdk
.PHONY : testsfdk

# fast build rule for target.
testsfdk/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/testsfdk.dir/build.make src/sfdk/CMakeFiles/testsfdk.dir/build
.PHONY : testsfdk/fast

#=============================================================================
# Target rules for targets named sfdkinfo

# Build rule for target.
sfdkinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfdkinfo
.PHONY : sfdkinfo

# fast build rule for target.
sfdkinfo/fast:
	$(MAKE) $(MAKESILENT) -f src/sfdk/CMakeFiles/sfdkinfo.dir/build.make src/sfdk/CMakeFiles/sfdkinfo.dir/build
.PHONY : sfdkinfo/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f third-party/google-benchmark/src/CMakeFiles/benchmark.dir/build.make third-party/google-benchmark/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) $(MAKESILENT) -f third-party/google-benchmark/src/CMakeFiles/benchmark_main.dir/build.make third-party/google-benchmark/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

#=============================================================================
# Target rules for targets named lib-benchmark

# Build rule for target.
lib-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib-benchmark
.PHONY : lib-benchmark

# fast build rule for target.
lib-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/lib-benchmark.dir/build.make benchmark/CMakeFiles/lib-benchmark.dir/build
.PHONY : lib-benchmark/fast

#=============================================================================
# Target rules for targets named allbenchmark

# Build rule for target.
allbenchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allbenchmark
.PHONY : allbenchmark

# fast build rule for target.
allbenchmark/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/allbenchmark.dir/build.make benchmark/CMakeFiles/allbenchmark.dir/build
.PHONY : allbenchmark/fast

#=============================================================================
# Target rules for targets named benchmarkinfo

# Build rule for target.
benchmarkinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmarkinfo
.PHONY : benchmarkinfo

# fast build rule for target.
benchmarkinfo/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/benchmarkinfo.dir/build.make benchmark/CMakeFiles/benchmarkinfo.dir/build
.PHONY : benchmarkinfo/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... allbenchmark"
	@echo "... allmodules"
	@echo "... allsfdk"
	@echo "... allsfdkexamples"
	@echo "... benchmarkinfo"
	@echo "... sfdkinfo"
	@echo "... testsfdk"
	@echo "... PALISADEsfdk"
	@echo "... benchmark"
	@echo "... benchmark_main"
	@echo "... lib-benchmark"
	@echo "... sfdk_tests"
	@echo "... sfdkobj"
	@echo "... simple-integers"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/carlosribeiro/Library/CloudStorage/OneDrive-UniversidadedeLisboa/VisualCode/palisade-sfdk/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

